In [64]:
import pandas as pd
df = pd.read_csv(r'D:\2025 lessons\AI+ML course amaliyot\Datasets\Food_Preference.csv')
df.head(20)

,Timestamp,Participant_ID,Gender,Nationality,Age,Food,Juice,Dessert
0,2019/05/07 2:59:13 PM GMT+8,FPS001,Male,Indian,24,Traditional food,Fresh Juice,Maybe
1,2019/05/07 2:59:45 PM GMT+8,FPS002,Female,Indian,22,Western Food,Carbonated drinks,Yes
2,2019/05/07 3:00:05 PM GMT+8,FPS003,Male,Indian,31,Western Food,Fresh Juice,Maybe
3,2019/05/07 3:00:11 PM GMT+8,FPS004,Female,Indian,25,Traditional food,Fresh Juice,Maybe
4,2019/05/07 3:02:50 PM GMT+8,FPS005,Male,Indian,27,Traditional food,Fresh Juice,Maybe
5,2019/05/07 3:03:34 PM GMT+8,FPS006,Male,Indian,24,Traditional food,Fresh Juice,Yes
6,2019/05/07 3:03:48 PM GMT+8,FPS007,Female,Indian,34,Traditional food,Fresh Juice,Yes
7,2019/05/07 3:04:37 PM GMT+8,FPS008,Male,Pakistani,24,Western Food,Carbonated drinks,Yes
8,2019/05/07 3:05:39 PM GMT+8,FPS009,Female,Indian,19,Traditional food,Fresh Juice,Yes
9,2019/05/07 3:06:53 PM GMT+8,FPS010,Female,Indian,16,Western Food,Fresh Juice,Yes
10,2019/05/07 3:07:26 PM GMT+8,FPS011,Male,Tanzanian,23,Traditional food,Fresh Juice,No
11,2019/05/07 3:07:36 PM GMT+8,FPS012,Female,Indian,22,Traditional food,Fresh Juice,Yes
12,2019/05/07 3:07:36 PM GMT+8,FPS013,Female,Indonesia,22,Traditional food,Fresh Juice,Maybe
13,2019/05/07 3:07:49 PM GMT+8,FPS014,Female,Indian,24,Western Food,Carbonated drinks,Yes
14,2019/05/07 3:09:06 PM GMT+8,FPS015,NaN,Muslim,27,Traditional food,Fresh Juice,Yes
15,2019/05/07 3:09:47 PM GMT+8,FPS016,Male,Pakistan,25,Traditional food,Fresh Juice,Maybe
16,2019/05/07 3:10:37 PM GMT+8,FPS017,Male,Maldivian,26,Traditional food,Fresh Juice,No
17,2019/05/07 3:12:29 PM GMT+8,FPS018,Male,MY,22,Traditional food,Fresh Juice,No
18,2019/05/07 3:13:11 PM GMT+8,FPS019,Female,Malaysian,38,Traditional food,Fresh Juice,Maybe
19,2019/05/07 3:18:07 PM GMT+8,FPS020,Female,Indian,31,Traditional food,Fresh Juice,Maybe

In [52]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 288 entries, 0 to 287
Data columns (total 8 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Timestamp       288 non-null    object
 1   Participant_ID  288 non-null    object
 2   Gender          284 non-null    object
 3   Nationality     288 non-null    object
 4   Age             288 non-null    int64
 5   Food            288 non-null    object
 6   Juice           288 non-null    object
 7   Dessert         288 non-null    object
dtypes: int64(1), object(7)
memory usage: 18.1+ KB

In [65]:
df = df.drop(columns=['Timestamp','Participant_ID'])
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 288 entries, 0 to 287
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Gender       284 non-null    object
 1   Nationality  288 non-null    object
 2   Age          288 non-null    int64
 3   Food         288 non-null    object
 4   Juice        288 non-null    object
 5   Dessert      288 non-null    object
dtypes: int64(1), object(5)
memory usage: 13.6+ KB

# Add 'Age category' feature

In [54]:
a  = df['Age']
print(len(a))

288

In [ ]:

def age_category(age):
    if age <=25:
        return 'Youth'
    elif 25< age <=40:
        return 'Middle'
    else:
        return 'Old'

df['Age category'] = df['Age'].apply(age_category)    # ! .apply() orqali yangi feature yasaldi

In [63]:
df['Age category'].value_counts()

Age category
Middle    142
Youth     111
Old        35
Name: count, dtype: int64

In [67]:
from sklearn.preprocessing import LabelEncoder
for col in  df.columns :
  if df[col].dtypes == 'object':
    df[col] = LabelEncoder().fit_transform(df[col])
df.head()

   Gender  Nationality  Age  Food  Juice  Dessert
0       1            3   24     0      1        0
1       0            3   22     1      0        2
2       1            3   31     1      1        0
3       0            3   25     0      1        0
4       1            3   27     0      1        0

In [ ]:
from sklearn.preprocessing import StandardScaler
df['Age'] = StandardScaler().fit_transform()

In [ ]:
from sklearn.feature_selection import mutual_info_classif